## merging 2 dataframes

In [1]:
#merging 2 dataframes
import numpy as np
import pandas as pd

In [2]:
# dataframe 1 employee info
employee= {
    'employee_id': [1,2,3,4,5],
    'Name':['john','anna','peter','linda','bob'],
    'department':['hr','it','finance','it','hr']
}
emp = pd.DataFrame(employee)

#dataframe 2 salary info
salaries={
    'employee_id': [1,2,3,6,7],
    'salary':[60000,80000,65000,70000,90000],
    'bonus':[5000,10000,7000,8000,12000]
}

sal= pd.DataFrame(salaries)

In [3]:
emp

   employee_id   Name department
0            1   john         hr
1            2   anna         it
2            3  peter    finance
3            4  linda         it
4            5    bob         hr

In [4]:
sal

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [5]:
pd.merge(emp,sal,on= 'employee_id', how='inner')
#gives common values

   employee_id   Name department  salary  bonus
0            1   john         hr   60000   5000
1            2   anna         it   80000  10000
2            3  peter    finance   65000   7000

In [6]:
pd.merge(emp,sal,on='employee_id',how='outer')
#includes all ids of both table

   employee_id   Name department   salary    bonus
0            1   john         hr  60000.0   5000.0
1            2   anna         it  80000.0  10000.0
2            3  peter    finance  65000.0   7000.0
3            4  linda         it      NaN      NaN
4            5    bob         hr      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [7]:
pd.merge(emp,sal,on='employee_id',how='left')
#include all ids of left or 1st table

   employee_id   Name department   salary    bonus
0            1   john         hr  60000.0   5000.0
1            2   anna         it  80000.0  10000.0
2            3  peter    finance  65000.0   7000.0
3            4  linda         it      NaN      NaN
4            5    bob         hr      NaN      NaN

In [8]:
pd.merge(emp,sal,on='employee_id',how='right')
#include all ids of right or 2nd table

   employee_id   Name department  salary  bonus
0            1   john         hr   60000   5000
1            2   anna         it   80000  10000
2            3  peter    finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [9]:
#concatination of 2 dataframes
a = pd.DataFrame(
    {
        'A':['a0','a1','a2'],
        'B':['b0','b1','b2'],
        'C':['c0','c1','c2']
    }
)

b = pd.DataFrame(
   {
        'A':['a3','a4','a5'],
        'B':['b3','b4','b5'],
        'C':['c3','c4','c5']
    } 
)

In [10]:
a

    A   B   C
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2

In [11]:
b

    A   B   C
0  a3  b3  c3
1  a4  b4  c4
2  a5  b5  c5

In [12]:
pd.concat([a,b])

    A   B   C
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
0  a3  b3  c3
1  a4  b4  c4
2  a5  b5  c5

pd.concat([b,a])

In [13]:
#to cancat row wise give axis = 1   , above by default axis =0
pd.concat([a,b], axis=1)

    A   B   C   A   B   C
0  a0  b0  c0  a3  b3  c3
1  a1  b1  c1  a4  b4  c4
2  a2  b2  c2  a5  b5  c5

## joining 2 dataframes

In [14]:
c = pd.DataFrame (
    {
      'name':[ 'alice','bob','charlli']
    },    index= [1,2,3]
)

d = pd.DataFrame(
    {
        'score' :[85,90,75] 
    }  , index= [2,3,4]
)

In [15]:
c

      name
1    alice
2      bob
3  charlli

In [16]:
d

   score
2     85
3     90
4     75

In [17]:
c.join(d,how='inner')

      name  score
2      bob     85
3  charlli     90

In [18]:
c.join(d,how='outer')

      name  score
1    alice    NaN
2      bob   85.0
3  charlli   90.0
4      NaN   75.0

## Group by

In [19]:
data1= {
    'category':['A','B','A','B','A','B','A','B'],
    'store':['s1','s1','s2','s2','s1','s2','s2','s1'],
     'sales':[100,200,150,250,120,180,200,300],
     'quantity':[10,15,12,18,8,20,15,25],
'date':pd.date_range('2023-01-01', periods=8)
}
grp= pd.DataFrame(data1)

In [20]:
grp

  category store  sales  quantity       date
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

In [21]:
#group by category and calculate the sum of sales
cat = grp.groupby('category')
cat
for i,v in cat:
    print(i)
    print(v) 
#this is only for how groups are created , optional

A
  category store  sales  quantity       date
0        A    s1    100        10 2023-01-01
2        A    s2    150        12 2023-01-03
4        A    s1    120         8 2023-01-05
6        A    s2    200        15 2023-01-07
B
  category store  sales  quantity       date
1        B    s1    200        15 2023-01-02
3        B    s2    250        18 2023-01-04
5        B    s2    180        20 2023-01-06
7        B    s1    300        25 2023-01-08

In [22]:
total=grp.groupby('category')['sales'].sum()
total

category
A    570
B    930
Name: sales, dtype: int64

In [23]:
#group by store and calculate the sum of sales
grp.groupby('store')['sales'].sum()

store
s1    720
s2    780
Name: sales, dtype: int64

In [24]:
#group by multiple columns then write in form of list 
grp.groupby(['category','store'])['sales'].sum()

category  store
A         s1       220
          s2       350
B         s1       500
          s2       430
Name: sales, dtype: int64

## Aggregation

In [25]:
grp

  category store  sales  quantity       date
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

In [26]:
grp['sales'].mean()

np.float64(187.5)

In [27]:
grp['quantity'].count()

np.int64(8)

In [29]:
abc = grp['sales'].agg(['sum','mean','min','max','count','std','median','var'])
abc

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
var       4364.285714
Name: sales, dtype: float64

## pivot tables

In [30]:
data2 = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
piv = pd.DataFrame(data2)

In [31]:
piv

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    928     43   John
1  2023-01-02       B   West    454     21   Mary
2  2023-01-03       C  North    554     12    Bob
3  2023-01-04       D  South    157     26  Alice
4  2023-01-05       A   East    897     85   John
5  2023-01-06       B   West    438     57   Mary
6  2023-01-07       C  North    851     75    Bob
7  2023-01-08       D  South    936     93  Alice
8  2023-01-09       A   East    363     84   John
9  2023-01-10       B   West    986     84   Mary
10 2023-01-11       C  North    663     73    Bob
11 2023-01-12       D  South    971     55  Alice
12 2023-01-13       A   East    831     32   John
13 2023-01-14       B   West    437     28   Mary
14 2023-01-15       C  North    503     50    Bob
15 2023-01-16       D  South    315     22  Alice
16 2023-01-17       A   East    819     78   John
17 2023-01-18       B   West    648     98   Mary
18 2023-01-19       C  North    647     48    Bob
19 2023-01-20       D  South    273     39  Alice

In [33]:
piv['Month'] = piv['Date'].dt.month_name()
piv['Quarter']= 'Q'+ piv['Date'].dt.quarter.astype(str)
piv

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    928     43   John  January      Q1
1  2023-01-02       B   West    454     21   Mary  January      Q1
2  2023-01-03       C  North    554     12    Bob  January      Q1
3  2023-01-04       D  South    157     26  Alice  January      Q1
4  2023-01-05       A   East    897     85   John  January      Q1
5  2023-01-06       B   West    438     57   Mary  January      Q1
6  2023-01-07       C  North    851     75    Bob  January      Q1
7  2023-01-08       D  South    936     93  Alice  January      Q1
8  2023-01-09       A   East    363     84   John  January      Q1
9  2023-01-10       B   West    986     84   Mary  January      Q1
10 2023-01-11       C  North    663     73    Bob  January      Q1
11 2023-01-12       D  South    971     55  Alice  January      Q1
12 2023-01-13       A   East    831     32   John  January      Q1
13 2023-01-14       B   West    437     28   Mary  January      Q1
14 2023-01-15       C  North    503     50    Bob  January      Q1
15 2023-01-16       D  South    315     22  Alice  January      Q1
16 2023-01-17       A   East    819     78   John  January      Q1
17 2023-01-18       B   West    648     98   Mary  January      Q1
18 2023-01-19       C  North    647     48    Bob  January      Q1
19 2023-01-20       D  South    273     39  Alice  January      Q1

In [34]:
pd.pivot_table(piv,values= 'Sales', index='Region', columns='Product',aggfunc='mean')

Product      A      B      C      D
Region
East     767.6    NaN    NaN    NaN
North      NaN    NaN  643.6    NaN
South      NaN    NaN    NaN  530.4
West       NaN  592.6    NaN    NaN

In [ ]:
#shift + tab to know the attributes of pivot_table
#by default table shows mean of sales , we can change it to median or other

In [35]:
pd.pivot_table(piv,values=['Sales','Units'],index='Product',columns='Region',aggfunc='median')
#the values attribute  should have the numeric values

         Sales                      Units
Region    East  North  South   West  East North South  West
Product
A        831.0    NaN    NaN    NaN  78.0   NaN   NaN   NaN
B          NaN    NaN    NaN  454.0   NaN   NaN   NaN  57.0
C          NaN  647.0    NaN    NaN   NaN  50.0   NaN   NaN
D          NaN    NaN  315.0    NaN   NaN   NaN  39.0   NaN

In [36]:
#cross Tab
# used for the counting purpose 

pd.crosstab(piv['Region'],piv['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

## operations

In [37]:
ope = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [38]:
ope

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [39]:
ope.shape

(5, 3)

In [40]:
ope.columns

Index(['A', 'B', 'C'], dtype='object')

In [41]:
ope.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [42]:
ope.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [43]:
ope['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

## dataframe applying functions

In [44]:
ope

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [45]:
def square(x):
    return x**2

In [46]:
ope['B'].apply(square)    # changes are not made in column

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [48]:
ope['B']= ope['B'].apply(square)
ope

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500

In [49]:
ope['D']= ope['A'].apply(lambda x : x*2)

In [50]:
ope

   A        B    C   D
0  1    10000  100   2
1  2   160000  200   4
2  3   810000  300   6
3  4  2560000  400   8
4  5  6250000  500  10